version: 2.1
orbs:
  codecov: circleci/codecov@0.0.4
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker-compose up -d
      - run:
          name: check linting
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app npm run lint
      - run:
          name: run tests
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app
      - codecov/upload:
          path: ./coverage/coverage-final.json
