version: 2.1
orbs:
  codecov: circleci/codecov@0.0.4
jobs:
  build:
    steps:
      - test
        machine: true
        working_directory: ~/repo
        steps:
          - checkout
          - run: docker-compose up -d
          - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app npm run test:coverage
          - codecov/upload:
            path: ./coverage/coverage-final.json
