version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
        - checkout
        - run: docker-compose up -d
        - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app


